---
- name: deployment
  hosts: 192.168.205.10
  gather_facts: "no"
  tasks:
    - name: Désactiver swap
      shell: swapoff -a
      become: yes
    - name: Copy app.yml
      copy: src=k8s-deploy.yml dest=/tmp
    - name: deployer
      shell: kubectl apply -f  /tmp/app.yml
